name: metrecicla_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  get: ^4.6.6
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.2
  cookie_jar: ^4.0.8
  dio: ^5.4.3
  dio_cookie_manager: ^3.1.1
  path_provider: ^2.1.3
  crypto: ^3.0.3
  encrypt: ^5.0.3
  http_interceptor: ^2.0.0-beta.8
  intl: ^0.19.0
  pdf: ^3.11.0
  printing: ^5.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/